import { RefundAnalysis } from "@/types/refund";

export interface RefundTemplates {
  // 免费层：第一封邮件（EN+ZH）带水印
  subject: string;
  body: string;
  subjectZh: string;
  bodyZh: string;
  // 付费层：追讨序列 + 客服话术
  premium: {
    followUps: { label: string; subject: string; body: string }[];
    zhFollowUps: { label: string; subject: string; body: string }[];
    chatScript: string;
    chatScriptZh: string;
  };
}

export function generateTemplates(analysis: RefundAnalysis): RefundTemplates {
  const { ocr, category } = analysis;
  const merchant = ocr.merchant;
  const amount = ocr.amount;
  const orderId = ocr.orderId;
  const date = ocr.date;
  const cur = ocr.currency === "EUR" ? "€" : ocr.currency === "GBP" ? "£" : ocr.currency === "CNY" ? "¥" : "$";
  const caseId = analysis.id;

  // ---- 免费层：第一封（礼貌版） ----
  const firstEn = firstEmail(category, { merchant, amount, orderId, date, cur });
  const firstZh = firstEmailZh(category, { merchant, amount, orderId, date, cur });
  const footer = (zh = false) =>
    zh
      ? `\n\n---\n由 Refund Hunter 生成 [Case ${caseId}] • 免费检测 • refundhunter.global`
      : `\n\n---\nGenerated by Refund Hunter [Case ${caseId}] • refundhunter.global`;

  // ---- 付费层：三连追讨 ----
  const followUps = followUpSequence(category, { merchant, amount, orderId, date, cur });
  const zhFollowUps = followUpSequenceZh(category, { merchant, amount, orderId, date, cur });
  const chatScript = chatFor(category, { merchant, amount, orderId, date, cur });
  const chatScriptZh = chatForZh(category, { merchant, amount, orderId, date, cur });

  return {
    subject: firstEn.subject,
    body: firstEn.body + footer(),
    subjectZh: firstZh.subject,
    bodyZh: firstZh.body + footer(true),
    premium: { followUps, zhFollowUps, chatScript, chatScriptZh },
  };
}

// ---------- 内部：按类别生成 ----------
interface Ctx { merchant: string; amount: string; orderId: string; date: string; cur: string }

function firstEmail(cat: string, c: Ctx) {
  const { merchant, amount, orderId, date, cur } = c;
  if (cat === "duplicate") return {
    subject: `Duplicate charge on ${date} - Request refund for order ${orderId}`,
    body: `Hello ${merchant} Support Team,\n\nI noticed I was charged twice for the same transaction on ${date} for ${cur}${amount} (Order: ${orderId}). This appears to be a duplicate processing error, and I have attached both receipts.\n\nCould you please refund the duplicate charge of ${cur}${amount} to my original payment method?\n\nThank you for your quick assistance.\n\nBest regards`,
  };
  if (cat === "renewal") return {
    subject: `Request refund for accidental renewal - ${merchant} - ${orderId}`,
    body: `Hello ${merchant} Support Team,\n\nI was charged ${cur}${amount} on ${date} for an automatic renewal (Order: ${orderId}). I did not intend to renew and have not used the service since.\n\nCould you please process a goodwill refund of ${cur}${amount}? If a full refund is not possible, a prorated refund would also be appreciated.\n\nThank you.`,
  };
  if (cat === "price_drop") return {
    subject: `Price protection request - lower price found for ${orderId}`,
    body: `Hello ${merchant} Support Team,\n\nI booked on ${date} (Order: ${orderId}) for ${cur}${amount}, and the same item is now available at a lower price. Under your price protection policy, could you please refund the difference? Screenshots with timestamps attached — my itinerary does not need to change.\n\nThank you.`,
  };
  if (cat === "overcharge") return {
    subject: `Incorrect charge of ${cur}${amount} - Request correction for ${orderId}`,
    body: `Hello ${merchant} Support Team,\n\nI was charged ${cur}${amount} on ${date} (Order: ${orderId}), but the expected amount was different. Please review and refund the overcharged amount. Invoice and payment record attached.\n\nThank you.`,
  };
  if (cat === "warranty") return {
    subject: `Warranty claim - defective product ${orderId}`,
    body: `Hello ${merchant} Support Team,\n\nI purchased on ${date} (Order: ${orderId}, ${cur}${amount}). The product developed a defect within the warranty period. Purchase proof and defect photos attached. Please advise on repair, replacement, or refund per your warranty policy.\n\nThank you.`,
  };
  return {
    subject: `Request review for charge ${cur}${amount} on ${date} - ${orderId}`,
    body: `Hello ${merchant} Support Team,\n\nI noticed a charge of ${cur}${amount} on ${date} (Order: ${orderId}) and would like to request a review for a possible refund. Happy to provide any additional information needed.\n\nThank you for your understanding.`,
  };
}

function firstEmailZh(cat: string, c: Ctx) {
  const { merchant, amount, orderId, date, cur } = c;
  const map: Record<string, [string, string]> = {
    duplicate: [`重复扣款申请退款 - 订单 ${orderId}`, `您好 ${merchant} 客服，\n\n我于 ${date} 被重复扣费 ${cur}${amount}（订单 ${orderId}），疑似系统重复处理，附件为两笔凭证。烦请原路退回 ${cur}${amount}，感谢！`],
    renewal: [`意外续费申请退款 - ${merchant}`, `您好 ${merchant} 客服，\n\n我于 ${date} 被自动续费 ${cur}${amount}（订单 ${orderId}），非本人意愿且续费后未使用。恳请善意退款 ${cur}${amount}，如无法全额，比例退款亦可。感谢理解！`],
    price_drop: [`价格保护申请 - 订单 ${orderId}`, `您好 ${merchant} 客服，\n\n我于 ${date} 预订订单 ${orderId}（${cur}${amount}），现同款有更低价格。按贵司价格保障政策恳请退还差价，附比价截图，行程无需变更。`],
    overcharge: [`错误收费申请更正 - ${orderId}`, `您好，我于 ${date} 被收取 ${cur}${amount}（订单 ${orderId}），与应付金额不符，烦请核实并退还多收部分。`],
    warranty: [`保修申请 - 订单 ${orderId}`, `您好，我于 ${date} 购买订单 ${orderId}（${cur}${amount}）出现故障，尚在保修期内。附购买凭证与故障照片，烦请按保修政策处理。`],
    other: [`申请复核 - ${date} 扣费 ${cur}${amount}`, `您好，我于 ${date} 有一笔 ${cur}${amount} 扣费（订单 ${orderId}），想咨询是否符合退款条件，烦请复核。`],
  };
  const [subject, body] = map[cat] || map.other;
  return { subject, body };
}

function followUpSequence(cat: string, c: Ctx): { label: string; subject: string; body: string }[] {
  const { merchant, amount, orderId, date, cur } = c;
  return [
    {
      label: "Follow-up #2 — Firm (send after 5-7 days silence)",
      subject: `Follow-up: unresolved refund request ${orderId} (${cur}${amount})`,
      body: `Hello ${merchant} Support Team,\n\nFollowing up on my refund request from ${date} (Order: ${orderId}, ${cur}${amount}) — I have not received a response.\n\n${cat === "renewal" ? "The charge was an accidental renewal and the service was unused. " : ""}Under consumer protection standards and your own refund guidelines, this request is reasonable. Please process the refund of ${cur}${amount} within 5 business days, or provide a case number and expected timeline.\n\nIf I do not receive a response, I will escalate via my payment provider's dispute process.\n\nRegards,`,
    },
    {
      label: "Follow-up #3 — Final / chargeback notice (send after 7 more days)",
      subject: `Final notice before payment dispute - Order ${orderId}`,
      body: `Hello ${merchant} Support Team,\n\nThis is my final attempt to resolve the ${cur}${amount} charge (Order: ${orderId}, dated ${date}) directly with you.\n\nDespite two previous requests, the issue remains unresolved. Unless the refund is processed within 72 hours, I will file a dispute with my card issuer (chargeback) and report the matter to the relevant consumer protection agency. A chargeback will also cost you a dispute fee — resolving this directly is in both our interests.\n\nI would much prefer the refund. Please confirm by reply.\n\nRegards,`,
    },
  ];
}

function followUpSequenceZh(cat: string, c: Ctx): { label: string; subject: string; body: string }[] {
  const { merchant, amount, orderId, date, cur } = c;
  return [
    {
      label: "追讨第2封 — 坚定版（5-7天无回复后发）",
      subject: `跟进：未处理的退款申请 ${orderId}（${cur}${amount}）`,
      body: `您好 ${merchant} 客服，\n\n跟进我 ${date} 提交的退款申请（订单 ${orderId}，${cur}${amount}），至今未收到回复。\n\n该请求合理且符合消费者保护规范及贵司退款条款。请在5个工作日内处理退款，或提供工单号与处理时限。\n\n如仍无回应，我将通过支付渠道发起争议（chargeback）流程。\n\n此致`,
    },
    {
      label: "追讨第3封 — 最后通牒（再等7天后发）",
      subject: `付款争议前最后通知 - 订单 ${orderId}`,
      body: `您好 ${merchant} 客服，\n\n这是我第三次就 ${cur}${amount} 扣费（订单 ${orderId}，${date}）与贵司沟通。\n\n前两次请求均未解决。如72小时内仍未退款，我将向发卡行发起拒付（chargeback），并向消费者保护机构投诉。拒付会产生争议费用，直接退款对双方成本更低。\n\n期待退款确认。\n\n此致`,
    },
  ];
}

function chatFor(cat: string, c: Ctx) {
  const { merchant, amount, orderId, date, cur } = c;
  const map: Record<string, string> = {
    duplicate: `Hi, I was charged twice on ${date} for ${cur}${amount} (order ${orderId}). This looks like a duplicate. Can you please refund the extra charge? I have both receipts ready.`,
    renewal: `Hi team, I was just charged ${cur}${amount} for auto-renewal on ${date} (order ${orderId}). I didn't mean to renew and haven't used it since. Could you please help with a goodwill refund?`,
    price_drop: `Hi, I booked ${orderId} on ${date} for ${cur}${amount} but now see the same one cheaper. Do you have price protection? Can you refund the difference? I have screenshots.`,
    overcharge: `Hi, I was charged ${cur}${amount} on ${date} for ${orderId} but this seems incorrect. Can you check and refund the difference?`,
    warranty: `Hi, my order ${orderId} from ${date} has a defect and should be under warranty. Can you help with repair/replacement or refund? I have photos.`,
    other: `Hi, I have a charge of ${cur}${amount} on ${date} for ${orderId} I'd like to check if it's refundable. Can you advise?`,
  };
  return map[cat] || map.other;
}

function chatForZh(cat: string, c: Ctx) {
  const { amount, orderId, date, cur } = c;
  const map: Record<string, string> = {
    duplicate: `你好，我 ${date} 被重复扣款 ${cur}${amount}（订单 ${orderId}），请帮忙退还多扣的一笔，两笔凭证我都有。`,
    renewal: `你好，${date} 被自动续费 ${cur}${amount}（订单 ${orderId}），我不是故意续费的且未使用，能帮忙善意退款吗？`,
    price_drop: `你好，订单 ${orderId}（${date}，${cur}${amount}）现在降价了，有价格保护吗？能退差价吗？我有截图。`,
    overcharge: `你好，${date} 订单 ${orderId} 被扣 ${cur}${amount}，金额不对，能核实并退差额吗？`,
    warranty: `你好，订单 ${orderId} 出现故障，还在保修期，能帮忙处理维修/换新/退款吗？有照片。`,
    other: `你好，${date} 有一笔 ${cur}${amount} 扣费（订单 ${orderId}），想确认是否符合退款条件。`,
  };
  return map[cat] || map.other;
}
